# k8s/apps/clinical-agentic-control-plane/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: cacp-api
  labels:
    app: cacp-api
spec:
  type: ClusterIP
  selector:
    app: cacp-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
