# k8s/base/namespaces.yaml
# Namespaces para la plataforma cl√≠nica.

apiVersion: v1
kind: Namespace
metadata:
  name: cacp-dev
  labels:
    app.kubernetes.io/part-of: clinical-platform
    environment: dev
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: cacp-prod
  labels:
    app.kubernetes.io/part-of: clinical-platform
    environment: prod
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: clinical-platform
    purpose: monitoring
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
